UoaWDCC/NZCSA-Frontend

src/App.js, src/pages/ForgotPassword.js
**Issue**: Page is required for the user to indicate they have forgotten their password
**Solution**: created forgot password page which allows users to send themselves an email to reset their password
**Risk**: None
**Reviewed by**: Melo, Tony, Kristy, Ziqing, Garfield
=> [NZCSA-013] Implement forgotPassword page

src/api/connectBackend.js, src/pages/ForgotPassword.js, src/pages/ResetPassword.js, src/pages/SignInSide.js
issue: need to finish function part for reset and forgot password
solution: add those basic functionalities
risk: none
reviewed by: Melo, Tony, Link, Kirsty, Zhiqing
=> [NZCSA-018] Finish the functionality for forgot/resetpassword page

src/components/EventCard.js
**Issues**
Require some card components to display the events for the users
**Solution**
Created a card component.
**Risk**
None
**Review**
Melo, Tony, Ziqing, Garfield, Linkun
=> [NZCSA-015] Implement events component

package-lock.json, src/pages/SignUp.js, yarn.lock
Issues:
Wrong Button color
Solution:
Change button color
Risk:
None
Review:
Tony, ZhiQing, Kirsty
=> [NZCSA-006] Implement Registration page

package-lock.json, package.json, src/components/EventCard.js, src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/EventGrid.js
**issues**
The event cards and the user information has not been connected to the backend
**solution**
Implemented the get-user-info api and event info api
**Risk**
no risk
**Review**
Melo, Ziqing, Tony, Linkun, Garfield
=> Nzcsa 036/event api integration

src/pages/Dashboard/EventDetail.js
**Issues**
Event detail page is missing an return button to the dashboard
**Solution**
Implemented a return button in the event detail page
**Risk**
No
Review:
Tony, Melo, Garfield, Linkun, Ziqing
=> Nzcsa 043/add back button eventdescription page

src/App.js, src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/EventGrid.js, src/pages/Dashboard/listItems.js
**Issues**
No your event page
**Solution**
Implemented the your event page
**Risk**
NO
**Review**
Tony, Melo, Ziqing, Garfield, Linkun
=> Nzcsa 042/finish your event page

package-lock.json, package.json, public/manifest.json, src/App.js, src/api/connectBackend.js, src/components/EventCard.js, src/components/Notification.js, src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/EventDetail.js, src/pages/Dashboard/EventGrid.js, src/pages/Dashboard/Payment.js, src/pages/Dashboard/PaymentForm.js, src/pages/SignInSide.js
Issue: no functionally for user sign up event button
Solution: Integrate users sign up event api
Risk: None
Reviewed by: Melo, Kirsty, Garfield, Tony, Linkun
=> NZCSA 037/integrate users sign up event api

.eslintignore, package-lock.json, src/App.js, src/components/CheckboxInputBtn.js, src/components/EventCard.js, src/components/MainCard.js, src/components/RadioIInputBtn.js, src/components/RandomImagePicker.js, src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/EventDetail.js, src/pages/Dashboard/EventGrid.js, src/pages/Dashboard/Payment.js, src/pages/Dashboard/PaymentForm.js, yarn.lock
**Describe the issue**
need to deploy
**Describe the solution**
fixed warning
**Describe the risk**
no risk
**To Be Reviewed By**
Melon, Link, Tony
=> [NZCSA-051] Deploy on Netlify

package.json, src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/EventDetail.js, src/pages/Dashboard/PaymentForm.js, src/pages/Dashboard/Upgrade.js, src/pages/Dashboard/UpgradeForm.js, yarn.lock
**Describe the issue**
need to deploy
**Describe the solution**
fixed warning
**Describe the risk**
no risk
**To Be Reviewed By**
Link, Tony
=> [NZCSA-065] Deploy on vercel

src/pages/ForgotPassword.js, src/pages/SignInSide.js
**Issue**
Email lower and upper case
**Solution**
Changed email to lowercase when signin or forgot password
**Risk**
no
**Review**
Tony, Melo, Ziqing, Linkun, Garfield
=> Bug fixing

src/api/connectBackend.js, src/pages/Dashboard/PaymentResultForm.js
Issue
Give longer time delay so no incorrect message
Solution
changed axios time
Risk
no
Review
Melo, Ziqing, Linkun, Garfield
=> [NZCSA-25] change axios time

src/components/VipBadget.js, src/pages/Dashboard/Dashboard.js
**Issue**
No clear indication on whether the user is a member or not
**Solution**
Added a badge for members
**Risk**
None
**Review**
Tony, Melo, Ziqing, Garfield, Linkun, Alex
=> Nzcsa 072/add vip badge

src/pages/Dashboard/UserInforDialog.js, yarn.lock
Issue
User needs to be able to see their account details
Solution
Redesigned account information popup
Risk
None
Review
Melo, Zhiqing, Garfield, Linkun, Alex, Kirsty
=> Nzcsa 081/add user icon in account section

src/pages/Dashboard/Dashboard.js
**Describe the issue**
Client: Implement search function
**Describe the solution**
use filter function
**Describe the risk**
no
**To Be Reviewed By**
Melon and Garfeild
=> [NZCSA-073] Client: Implement search function

src/pages/Dashboard/Dashboard.js
Describe the issue
The search function can not be used
Describe the solution
Use previous version
Describe the risk
no
To Be Reviewed By
Link, Garfeild
=> [NZCSA-078] Fix search Bug

package.json, src/components/MainCard.js, src/components/SliderImageCard.js, src/pages/Dashboard/Dashboard.js
Issue:
no image slide show for the main card
Solution:
Implemented a image slide show
Risk:
None
Review:
Tony, Melo, Zhiqing, Garfield, Alex, Linkun, Jack
=> [NZCSA-078] Client: Image slideshow on home page

src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/EventGrid.js
**Describe the issue**
Search bug
**Describe the solution**
fix it
**Describe the risk**
no
**To Be Reviewed By**
Melon and Garfield
=> Nzcsa 073 client implement search function fix

src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/EventGrid.js
Reverts UoaWDCC/NZCSA-Frontend#48
=> Revert "Nzcsa 073 client implement search function fix"

src/components/EventCard.js, src/pages/Dashboard/Dashboard.js, src/pages/Dashboard/EventDetail.js, src/pages/Dashboard/EventGrid.js
Issue
previous/current/future event tabs not functioning
Solution
implement this function
Risk
None
Review
Melo, Tony, Garfield, Linkun, Alex, Kirsty
=> NZCSA-079/Previous-Current-Future-event-tabs-in-home-page

README.md, src/pages/Dashboard/PaymentForm.js
=> Disable 2021 membership registration payment

src/pages/Dashboard/EventDetail.js, src/pages/Dashboard/YourEventDetail.js
Fix the position of the close button to the top of the page.
=> [NZCSA-95] Fix the position of the close button of the event in mobile view

src/components/EventCard.js, src/pages/Dashboard/EventDetail.js
Format popups by writing our own pop up dialog instead of using an imported one. This allows users to view the full pop up on mobile devices.
=> [NZCSA-98] Format popups

src/pages/Dashboard/Dashboard.js, src/pages/SignInSide.js, src/utils/pwaUtils.js
Issue
User is unaware that NZCSA web app is installable
Solution
Added install banner for IOS and Android to login and dashboard screen
Risk
None
Review
Melo, Garfield, Linkun, Alex, Kirsty, Nancy, Zhiqing
=> [NZCSA-100] Install banner for sign-in page

src/pages/Dashboard/YourEventDetail.js
Issue
Wechat QR code distorted on IOS
Solution
Add width and height for image
Risk
None
Review
Alex, Kirsty
=> [BUG-02] Wechat QR code distorted on IOS

src/pages/Dashboard/PaymentForm.js
=> Enabled payment function

src/components/EventCard.js
Not showing right price when click in dashboard
=> fix: registration button

src/pages/Dashboard/UserInforDialog.js
**Issue**: user account display unclear
**Solution**: edited user account display
**Risk**: /
=> Nzcsa 109 update the user account display

src/pages/SignUp.js
Frontend validation for register with school email (suffix with `ac.nz`)
=> NZCSA-113 Validate register with school email

package.json, src/components/RadioIInputBtn.js, src/pages/Dashboard/UpgradeForm.js, src/pages/SignUp.js
Frontend validation for all required fields in upgrade form. Submission will be blocked if any required field is empty.
=> NZCSA 114 Validate upgrade form input fields

src/pages/SignUp.js
reverted ac.nz email requirement
tested locally on 3000
*Provide screenshots of what has been implemented. Leave blank if not applicable*
*(Leave blank if not applicable)*
- [y ] My code follows the style guidelines of this project
- [ y] I have performed a self-review of my own code
- [ y] I have commented my code, particularly in hard-to-understand areas
- [ y] My changes generate no new warnings
- [ y] I have checked my code and corrected any misspellings
=> revert .ac.nz

.github/ISSUE_TEMPLATE/issue_template.md, src/pages/Dashboard/Dashboard.js, src/pages/SignInSide.js, src/pages/SignUp.js
Added update alert in the signin side when in deployment is availiable
Did manual deployment test
*Provide screenshots of what has been implemented. Leave blank if not applicable*
*(Leave blank if not applicable)*
=> add new update in signin side

src/pages/Dashboard/PaymentForm.js
Wechat pay button is added back while Polipay button is commented out
Tested using wechat pay
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] I have checked my code and corrected any misspellings
=> Disable Polipay and enable WeChat Pay

src/pages/Dashboard/PaymentForm.js
=> enabled polipay

src/components/Copyright.js, src/components/DarkModeSwitch.js, src/components/EventCard.js, src/pages/SignInSide.js
Documented Copyright.js, DarkModeSwitch.js, EventCard.js and SingInSide.js and added comemtns. 
toggleThemeChange and handleChange functions in DarkModeSwitch.js are not used (tested). Miscellaneous lines and commented can be reformated. 
/
/
*(Leave blank if not applicable)*
=> documentation for Copyright, DarkModeSwitch, EventCard and SignInSide

src/pages/Dashboard/EventDetail.js, src/pages/Dashboard/EventGrid.js, src/pages/Dashboard/Payment.js, src/pages/Dashboard/SponsorGrid.js, src/pages/Dashboard/Upgrade.js, src/pages/Dashboard/UpgradeForm.js
Documented Upgrade.js and UpgradeForm.js using jsdoc, code that can be deleted are commented out and tested to perpare for code refactoring.
=> docuemented upgrade and upgradeform

src/pages/Dashboard/Payment.js
Added useStyles() back to payment.js
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ x] I have checked my code and corrected any misspellings
=> small bug in payment
